### ISSUE TITLE
Default --model_wts_path is absent in Google Drive Share

### ISSUE THREAD

**Issue by tashrifbillah** [NYUMedML/BrainSeg#1]
Folks, you forgot to put the default `--model_wts_path` in your [Google Drive Link](https://drive.google.com/file/d/1-reUDvwBhSOUqOa48W9Vgh_LN3F5ZRjQ/view).

```
FileNotFoundError: [Errno 2] No such file or directory: './saved_model_wts/dense_unet_back2front_finetuned.pth'

**Comment by tashrifbillah** [comment]
Hi @narges-rzv , I noticed your LinkedIn [post](https://www.linkedin.com/posts/narges-razavian-512b7635_dartseg-brainmri-parcellation-activity-6602250507601891328-CGlz) a while back.

**Comment by tashrifbillah** [comment]
See my comment [here](https://github.com/NYUMedML/DARTS/pull/4/commits/b9ba39b6450221950c85ccf66f18fd6013624e1b#r358040281).

**Comment by aakashrkaku** [comment]
Addressed the issue. Thank you for pointing it out.
